### ISSUE TITLE
migration checklist

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#217]
- [x] migrate forum topics to discourse
- [x] generate fresh JSON data in docker-openabm (DownloadCount + all migration json files)
- [x] copy model filesystem + pictures to prod host
- [x] redirect www.comses.net to fallback maintenance nginx
- [x] rerun cms migration
- [x] import comses 2017 users
- [x] set up openabm.org nginx with redirects

**Comment by alee** [comment]
Custom steps needed:

- configured nginx 1.12 repo on openabm.asu.edu and set up manual ssl conf
- manually added github oauth keys to prod's SocialApp models, not sure why they got wiped out. orcid provider will need the same. Possibly destroyed by the import_comses_2017_users management command
