### ISSUE TITLE
testing checklist

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#221]
- [x] verify every page loads
- [x] verify contact email works
- [x] check google webmaster toolkit / search console / robots.txt
- [x] check google analytics
- [ ] verify all form submissions
- [ ] verify that this list is complete
